#!/bin/sh
# Renders the jack-o'-lantern favicon into static/favicon.png and, wrapping
# that same raster, static/favicon.svg.
#
#   tools/make-favicon.sh
#
# Why this is not just <text>🎃</text> in an SVG, which is what it used to be:
# a browser draws an SVG favicon in a sandbox with no page context and no
# guarantee of the system emoji font, so the glyph falls back to the notdef
# box — Zach reported it as "a weird little circle". A favicon has to carry
# its own pixels.
#
# Same two-pass trick as make-og.sh, and the same reason. This host has no
# colour emoji font at all, so the render happens in a throwaway Debian
# container; and Noto Color Emoji is a CBDT bitmap font, which librsvg
# flattens to a black silhouette, so Pillow rasterises the glyph with
# embedded_color=True at 109px — the only strike CBDT carries — and everything
# downstream treats it as an image rather than as text.
set -eu

cd "$(dirname "$0")/.."
REPO="$PWD"

docker run --rm \
  -v "$REPO/static:/out" \
  -e UID_GID="$(id -u):$(id -g)" \
  debian:bookworm-slim sh -c '
set -eu
apt-get update -qq >/dev/null
apt-get install -y -qq fonts-noto-color-emoji python3-pil >/dev/null

python3 - <<"PY"
import base64
from PIL import Image, ImageDraw, ImageFont

SIZE = 256

font = ImageFont.truetype("/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf", 109)
img = Image.new("RGBA", (140, 140), (0, 0, 0, 0))
ImageDraw.Draw(img).text((70, 70), "\U0001F383", font=font,
                         embedded_color=True, anchor="mm")

# Crop to the glyph and letterbox it square, so the pumpkin keeps its aspect
# ratio and sits centred however the browser scales the icon.
glyph = img.crop(img.getbbox())
scale = SIZE / max(glyph.size)
glyph = glyph.resize((max(1, round(glyph.width * scale)),
                      max(1, round(glyph.height * scale))), Image.LANCZOS)
canvas = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
canvas.paste(glyph, ((SIZE - glyph.width) // 2, (SIZE - glyph.height) // 2))
canvas.save("/out/favicon.png")

# The SVG is the same pixels in a scalable wrapper. It is a data: URI and not
# an href because an SVG favicon is rendered with external loads blocked, so a
# referenced file would come back empty.
b64 = base64.b64encode(open("/out/favicon.png", "rb").read()).decode()
open("/out/favicon.svg", "w").write(
    "<!-- Generated by tools/make-favicon.sh. The jack-o-lantern (U+1F383)\n"
    "     from Noto Color Emoji, rasterised and inlined: a favicon cannot\n"
    "     rely on the reader having an emoji font. Edit the script, not this. -->\n"
    "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 %d %d\"\n"
    "     role=\"img\" aria-label=\"Jack-o-lantern\">\n"
    "  <image width=\"%d\" height=\"%d\" href=\"data:image/png;base64,%s\"/>\n"
    "</svg>\n" % (SIZE, SIZE, SIZE, SIZE, b64))
PY

chown "$UID_GID" /out/favicon.png /out/favicon.svg
'

echo "wrote $REPO/static/favicon.png and $REPO/static/favicon.svg"
ls -l "$REPO/static/favicon.png" "$REPO/static/favicon.svg"
