const A=require('node:assert/strict'),{chromium}=require('playwright-core');
const mode=process.argv[2],url=process.argv[3];
const audio=()=>{window.__audio={starts:0};class C{constructor(){this.sampleRate=48000;this.destination={};this.currentTime=0}resume(){return Promise.resolve()}createBuffer(c,n,r){const a=new Float32Array(n);return{length:n,duration:n/r,sampleRate:r,getChannelData:()=>a,copyToChannel:s=>a.set(s)}}createBufferSource(){return{connect(){},disconnect(){},start(){__audio.starts++},stop(){}}}}window.AudioContext=C;window.webkitAudioContext=C};
const cases={
"shiftmask":async(p,click,select,check)=>{for(let i=0;i<5;i++)await check('strip-mask-'+i,i===0||i===2);const read=()=>p.locator('[id^="strip-mask-"][type="checkbox"]').evaluateAll(es=>es.map(e=>e.checked));const totals=await p.locator('#working-strip meter').evaluateAll(es=>es.map(e=>e.value));await click('strip-mask-right');A.deepEqual(await read(),[false,true,false,true,false]);await click('strip-mask-left');A.deepEqual(await read(),[true,false,true,false,false]);A.deepEqual(await p.locator('#working-strip meter').evaluateAll(es=>es.map(e=>e.value)),totals);A(await p.locator('#strip-undo').isDisabled());},
"scalemask":async(p,click,select,check)=>{for(let i=0;i<5;i++)await check('strip-mask-'+i,i===0||i===2);await click('strip-mask-finish');await click('strip-mask-half');A.deepEqual(await p.locator('#working-strip meter').evaluateAll(es=>es.map(e=>e.value)),[4,0,8,0,0]);await click('strip-undo');A.deepEqual(await p.locator('#working-strip meter').evaluateAll(es=>es.map(e=>e.value)),[8,0,16,0,0]);await click('strip-mask-double');A.deepEqual(await p.locator('#working-strip meter').evaluateAll(es=>es.map(e=>e.value)),[16,0,32,0,0]);await click('strip-undo');A.deepEqual(await p.locator('#working-strip meter').evaluateAll(es=>es.map(e=>e.value)),[8,0,16,0,0]);}
};
const messages={"shiftmask": "the five-band mask wraps left and right without adding light or history", "scalemask": "only checked bands halve or double their accumulated light in one Undo"};

(async()=>{A(cases[mode]);const b=await chromium.launch({args:['--no-sandbox']});try{for(const width of [390,1280]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});await p.addInitScript(audio);const errors=[];p.on('pageerror',e=>errors.push(e.message));A.equal((await p.goto(url)).status(),200);await p.waitForTimeout(120);
const reveal=async l=>{const ids=await l.evaluate(e=>{let a=[];for(let n=e.parentElement;n;n=n.parentElement)if(n.tagName==='DETAILS'&&!n.open)a.unshift(n.id);return a});for(const id of ids){A(id);await p.locator('#'+id+'>summary').scrollIntoViewIfNeeded();await p.locator('#'+id+'>summary').click()}};
const click=async id=>{const l=p.locator('#'+id);await reveal(l);await l.scrollIntoViewIfNeeded();A(await l.isEnabled(),id+' enabled');A(await l.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===e||e.contains(h)}),id+' hit');await l.click();await p.waitForTimeout(70)};
const select=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.selectOption(v);await p.waitForTimeout(70)};
const check=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.setChecked(v);await p.waitForTimeout(70)};
await cases[mode](p,click,select,check);A.deepEqual(errors,[]);A(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`/tmp/planner-oct9-${mode}-${width}.png`,fullPage:true});await p.close();}console.log(messages[mode]);}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
